### ISSUE TITLE
Out of memory error restoring Ops Manager

### ISSUE THREAD

**Issue by aboik** [pivotalservices/cfbackup#45]
I'm getting a "runtime: out of memory" error while trying to restore Ops Manager using cfops. The installation.zip file is larger (4.4GB) than the memory on the VM I'm running cfops from (4GB), but I thought the issue with large file uploads had been resolved in a previous release.

**Comment by xchapter7x** [comment]
thanks for reporting this. we are looking into it now.

**Comment by xchapter7x** [comment]
@aboik 
should be fixed by story #112060893

new release should reflect the changes.
https://github.com/pivotalservices/cfops/releases/tag/v2.0.33

**Comment by aboik** [comment]
Now there's an EOF error when uploading the installation file for ops manager with LargeMultiPartUpload. Is this why it was reverted to MultiPartUpload before?

2016/01/20 15:03:16 D0120 15:03:16.357352 13083 large_multipart.go:17] adding params for request: %!(EXTRA map[string]string=map[password:xxx])
2016/01/20 15:04:16 E0120 15:04:16.396075 13083 opsmanager.go:196] error uploading installation: Post https://10.116.61.40/api/installation_asset_collection: EOF
2016/01/20 15:04:16 E0120 15:04:16.397252 13083 createCliCommand.go:42] there was an error: Post https://10.116.61.40/api/installation_asset_collection: EOF running restore on ops-manager

**Comment by xchapter7x** [comment]
The issue was, that the LargeMultiPartUpload was not adding the proper post parameter fields, which are now required by ops manager 1.6. We reverted back to MultiPartUpload, while we added the fields to LargeMultiPartUpload. Most are not immediately affected by the large file constraint on restore, which is why we took that approach. That is now complete. 

It looks like you are running into a different issue now.

Give us a bit to keep digging on your specific issue. We'll keep you posted.

**Comment by aboik** [comment]
Looks like this is fixed in cfops v2.0.35, so I was able to successfully restore the ops mgr tile.. one question, do I just 'apply changes' in ops mgr and then run cfops restore for the elastic runtime?

**Comment by xchapter7x** [comment]
correct. you will need to manually click apply changes or curl the apply changes endpoint.
that is a manual gate put in place to make sure we are not pushing up potentially destructive changes.

let us know how the ER restore goes. 
closing this issue for now.
